### ISSUE TITLE
Allow types to be spliced into a typeof keyword to make reflection and meta-programming easier

### ISSUE THREAD

**Issue by 7sharp9** [fsharp/fslang-suggestions#698]
# Title of Suggestion

I propose we allow types to be spliced into `typeof<...>` to make reflection and meta-programming in F# easier.  

The existing way of approaching this problem in F# is to do this manually with the following code:

Imagine we have a reference to a type _fieldType_ :

```
type FieldType = class end
let fieldType = typeof<FieldType>
```

To create an instance of an `Option<fieldType>` would require the following code:
```
typedefof<Option<_>>.MakeGenericType(fieldType)
```

This in itself is not too bad, but what if we needed to make a type which looked more like this:

```
IReadOnlyDictionary<String, JToken> -> Result<Option<fieldType> -> Option<nextFieldType> -> recordType, String>
```
This requires substantially more code and can quickly get out of hand : _also note the use if a helper function `makeFunctionTypeFromElements` which is not detailed below_ :

```
 let domain = typeof<IReadOnlyDictionary<String, JToken>>
 let range =
     let currentField = typedefof<Option<_>>.MakeGenericType(fieldType)
     let nextField = typedefof<Option<_>>.MakeGenericType(nextFieldType)
     let functionType = makeFunctionTypeFromElements [currentField; nextField; recordType]
     typedefof<Result<_,_>>.MakeGenericType([|functionType; typeof<string>|])
 let decoderType = Reflection.FSharpType.MakeFunctionType(domain, range)
```

This could be simplified to the following if `typeof` allowed the splicing of types via a construct like `%typeInstance`:
```
typeof<IReadOnlyDictionary<String, JToken> -> Result<Option<%fieldType> -> Option<%nextFieldType> -> %myRecord, String>>
```

## Pros and Cons 

The advantages of making this adjustment to F# are simplifying the creation of generic types for meta programming

The disadvantages of making this adjustment to F# are adding extra complexity to F#.

## Extra information

Estimated cost (S/M): 

Related suggestions: (put links to related suggestions here)
#670 is related as that pertains to splicing of types into an untyped quotation.

## Affidavit (please submit!)

Please tick this by placing a cross in the box:
* [x] This is not a question (e.g. like one you might ask on [stackoverflow](http://stackoverflow.com)) and I have searched stackoverflow for discussions of this issue
* [x] I have [searched both open and closed suggestions on this site](http://github.com/fsharp/fslang-suggestions/issues) and believe this is not a duplicate
* [x] This is not something which has obviously "already been decided" in previous versions of F#.  If you're questioning a fundamental design decision that has obviously already been taken (e.g. "Make F# untyped") then please don't submit it.

Please tick all that apply:
* [x] This is not a breaking change to the F# language design
* [x] I or my company would be willing to help implement and/or test this

**Comment by dsyme** [comment]
This seems entirely reasonable, though would complicate the code generation for typeof, which is currently very simple.  Do you have a prototype?

**Comment by 7sharp9** [comment]
@dsyme Not currently, although I could work towards one

**Comment by 7sharp9** [comment]
`(# "ldtoken !0" type('T) : System.RuntimeTypeHandle #)`
Is nice and simple :-)

**Comment by dsyme** [comment]
Yes :)

**Comment by 7sharp9** [comment]
@dsyme  Im guessing that the work involved would have to be in the parser as the typeof function only recieves a type, or adding a new function

**Comment by dsyme** [comment]
> @dsyme Im guessing that the work involved would have to be in the parser as the typeof function only recieves a type, or adding a new function

You'd add a splicing syntax into types, like we do for expressions. it could only be for use in typeof, just like expression splicing is only for use in `<@ ... @>`.  I think the construct may need parantheses in some form since you're moving from type syntax to expression syntax, e.g.

    typeof<list<%(ty)>>

To be honest calling `<@ ... @>` simply `exprof(...)` would have made a lot of sense but hey.

One simple implementation would be to to emit either a generic utility method and a reflection-instantiate-then-invoke call of that method, e.g. 

    typeof<list<%(ty)>>

becomes

    Type PrivateHelperMethod<T>() { return typeof<list<T>> }

    methodinfoof(PrivateHelperMethod).MakeGenericMethod( [| ty |]).Invoke(null)

or something like that.

**Comment by abelbraaksma** [comment]
@7sharp9, you closed this, even though it a approved and upvoted? Why, if I may ask?

**Comment by cartermp** [comment]
This is staying open.

**Comment by dsyme** [comment]
It feels like #670 is a simpler route.  Then types can be spliced and quoted using an expression like this:

```fsharp
<@ Unchecked.defaultof<IReadOnlyDictionary<String, JToken> -> Result<Option<%%fieldType> -> Option<%%nextFieldType> -> %%recordType, String>> @>.Type
```
This can half be done by using a helper function
```fsharp
let makeMyType<'FieldType, 'NextFieldType, 'RecordType> () = 
    <@ Unchecked.defaultof<IReadOnlyDictionary<String, JToken> -> Result<Option<'FieldType> -> Option<'NextFieldType> -> 'RecordType, String>> @>.Type
```
Then doing a `MakeGenericMethod` call instantiating just those three type parameters.

**Comment by dsyme** [comment]
So I'll close this in favour of #670
